apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-api-deployment
  namespace: default
spec:
  replicas: 1 # Começaremos com 1 para o teste
  selector:
    matchLabels:
      app: minimal-api
  template:
    metadata:
      labels:
        app: minimal-api
    spec:
      containers:
      - name: minimal-api-container
        image: harbor.homelab.local/test-api/minimal-api:2d2b53632140d3b1dd4da72109d6a0c6be7683b2
        ports:
        - containerPort: 8080 # A porta que expomos no Dockerfile
